// COLORS TECS
import { Tecs } from "./dataTecs";

export const dataGridItem = [
  {
    name: Tecs.c_react[0],
    color: Tecs.c_react[1],
    text: Tecs.c_csharp[2],
    link: Tecs.c_csharp[3],
    img: Tecs.c_react[4],
  },
  {
    name: Tecs.c_redux[0],
    color: Tecs.c_redux[1],
    text: Tecs.c_redux[2],
    link: Tecs.c_redux[3],
    img: Tecs.c_redux[4],
  },
  {
    name: Tecs.c_react_native[0],
    color: Tecs.c_react_native[1],
    text: Tecs.c_react[2],
    link: Tecs.c_react[3],
    img: Tecs.c_react_native[4],
  },
  {
    name: Tecs.c_unity[0],
    color: Tecs.c_unity[1],
    text: Tecs.c_css[2],
    link: Tecs.c_css[3],
    img: Tecs.c_unity[4],
  },
  {
    name: Tecs.c_nodejs[0],
    color: Tecs.c_nodejs[1],
    text: Tecs.c_html[2],
    link: Tecs.c_html[3],
    img: Tecs.c_nodejs[4],
  },
  {
    name: Tecs.c_mysql[0],
    color: Tecs.c_mysql[1],
    text: Tecs.c_js[2],
    link: Tecs.c_js[3],
    img: Tecs.c_mysql[4],
  },
  {
    name: Tecs.c_js[0],
    color: Tecs.c_js[1],
    text: Tecs.c_react_native[2],
    link: Tecs.c_react_native[3],
    img: Tecs.c_js[4],
  },
  {
    name: Tecs.c_jquery[0],
    color: Tecs.c_jquery[1],
    text: Tecs.c_unity[2],
    link: Tecs.c_unity[3],
    img: Tecs.c_jquery[4],
  },
  {
    name: Tecs.c_html[0],
    color: Tecs.c_html[1],
    text: Tecs.c_nodejs[2],
    link: Tecs.c_nodejs[3],
    img: Tecs.c_html[4],
  },
  {
    name: Tecs.c_git[0],
    color: Tecs.c_git[1],
    text: Tecs.c_mysql[2],
    link: Tecs.c_mysql[3],
    img: Tecs.c_git[4],
  },
  {
    name: Tecs.c_css[0],
    color: Tecs.c_css[1],
    text: Tecs.c_jquery[2],
    link: Tecs.c_jquery[3],
    img: Tecs.c_css[4],
  },
  {
    name: Tecs.c_csharp[0],
    color: Tecs.c_csharp[1],
    text: Tecs.c_git[2],
    link: Tecs.c_git[3],
    img: Tecs.c_csharp[4],
  },
  {
    name: Tecs.c_typescript[0],
    color: Tecs.c_typescript[1],
    text: Tecs.c_typescript[2],
    link: Tecs.c_typescript[3],
    img: Tecs.c_typescript[4],
  },
  {
    name: Tecs.c_styled[0],
    color: Tecs.c_styled[1],
    text: Tecs.c_styled[2],
    link: Tecs.c_styled[3],
    img: Tecs.c_styled[4],
  },
  {
    name: Tecs.c_sass[0],
    color: Tecs.c_sass[1],
    text: Tecs.c_sass[2],
    link: Tecs.c_sass[3],
    img: Tecs.c_sass[4],
  },
  {
    name: Tecs.c_materialui[0],
    color: Tecs.c_materialui[1],
    text: Tecs.c_materialui[2],
    link: Tecs.c_materialui[3],
    img: Tecs.c_materialui[4],
  },
  {
    name: Tecs.c_reactbt[0],
    color: Tecs.c_reactbt[1],
    text: Tecs.c_reactbt[2],
    link: Tecs.c_reactbt[3],
    img: Tecs.c_reactbt[4],
  },
  {
    name: Tecs.c_materialize[0],
    color: Tecs.c_materialize[1],
    text: Tecs.c_materialize[2],
    link: Tecs.c_materialize[3],
    img: Tecs.c_materialize[4],
  },
  {
    name: Tecs.c_github[0],
    color: Tecs.c_github[1],
    text: Tecs.c_github[2],
    link: Tecs.c_github[3],
    img: Tecs.c_github[4],
  },
  {
    name: Tecs.c_lottie[0],
    color: Tecs.c_lottie[1],
    text: Tecs.c_lottie[2],
    link: Tecs.c_lottie[3],
    img: Tecs.c_lottie[4],
  },
  {
    name: Tecs.c_axios[0],
    color: Tecs.c_axios[1],
    text: Tecs.c_axios[2],
    link: Tecs.c_axios[3],
    img: Tecs.c_axios[4],
  },
  {
    name: Tecs.c_react_icons[0],
    color: Tecs.c_react_icons[1],
    text: Tecs.c_react_icons[2],
    link: Tecs.c_react_icons[3],
    img: Tecs.c_react_icons[4],
  },
  {
    name: Tecs.c_sweetalert[0],
    color: Tecs.c_sweetalert[1],
    text: Tecs.c_sweetalert[2],
    link: Tecs.c_sweetalert[3],
    img: Tecs.c_sweetalert[4],
  },
  {
    name: Tecs.c_react_router[0],
    color: Tecs.c_react_router[1],
    text: Tecs.c_react_router[2],
    link: Tecs.c_react_router[3],
    img: Tecs.c_react_router[4],
  },
  {
    name: Tecs.c_react_navigation[0],
    color: Tecs.c_react_navigation[1],
    text: Tecs.c_react_navigation[2],
    link: Tecs.c_react_navigation[3],
    img: Tecs.c_react_navigation[4],
  },
  {
    name: Tecs.c_react_leaflet[0],
    color: Tecs.c_react_leaflet[1],
    text: Tecs.c_react_leaflet[2],
    link: Tecs.c_react_leaflet[3],
    img: Tecs.c_react_leaflet[4],
  },
];
